### ISSUE TITLE
More Analytics

### ISSUE THREAD

**Issue by rahulrajpl** [coder-amey/COVID-19-India_Data#1]
Hey Amey,

Came across your dataset and on top of it I have created a Hans Rosling Style Analytics. Take a look here: http://randomwalk.in/covid19India/

I hope you will keep updating the dataset. I have added you as a collaborator. I think this is the only Hans Rosling style analytics publically available. So let us keep this running. It might be useful for somebody. 

-Regards, Rahul

**Comment by coder-amey** [comment]
Hi Rahul,  

Your work is amazing!  
I will certainly keep updating the dataset as regularly as the source provides it.  

Thanks a lot for adding me as a collaborator!  
Glad to see you put this data to such a great use.  
Let us definitely keep it running!  

Stay safe.

Regards,  
Amey.
