### ISSUE TITLE
Minor issue with the data collection

### ISSUE THREAD

**Issue by rahulrajpl** [coder-amey/COVID-19-India_Data#3]
Hey Amey,

Take a look at this
![image](https://user-images.githubusercontent.com/279503/78453904-4c9f8380-76b2-11ea-8fb9-f4f051630492.png)

Till 27 Mar, it was Telangana after that it is Telengana, due to which there is an inconsistency in the data while plotting (as you can see above). Would you please clean the data to be 'Telengana' for all the records on and prior to 27 Mar?

Thanks, Rahul

**Comment by coder-amey** [comment]
Thanks for bringing this up.  
I'll work on it and get it done by EOD.  

Cheers,  
Amey.

**Comment by coder-amey** [comment]
All respective entries have been changed to "Telangana".  
Issue resolved.  

Cheers!
